services:
  jenkinsapp:
    image: jenkinsapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jenkinsapp-postgresql:5432/jenkinsapp
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://jenkinsapp-postgresql:5432/jenkinsapp
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      jenkinsapp-postgresql:
        condition: service_healthy
  jenkinsapp-postgresql:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=jenkinsapp
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
